language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t $u97is/dtp-client -f ./Dockerfile.dev .

script:
    - docker run -e CI=true $u97is/dtp-client npm test

after_success:
    - docker build -t $u97is/dtp-client .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $u97is/dtp-client

deploy:
    provider: firebase
    token: $FIREBASE_AUTH_TOKEN
    message: "Deploying to firebase..."
    on:
        branch: master