language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t lu97is/dtp-client -f Dockerfile.dev .

script:
    - docker run -e CI=true lu97is/dtp-client npm test

after_success:
  - test $TRAVIS_BRANCH = 'master' && 
    docker build -t lu97is/dtp-client --build-arg FIREBASE_AUTH_TOKEN=$FIREBASE_AUTH_TOKEN . &&
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin &&
    docker push lu97is/dtp-client