/* ----------------------------------------------
 * Generated by Animista on 2020-4-12 15:34:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

import styled, { keyframes } from 'styled-components';

// define all animations
const FadeInFwd = keyframes`
  0% {
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    transform: translateZ(0);
    opacity: 1;
  }
`;

type AllAnimations = 'FadeInFwd' | 'error';

export type AnimationType = {
  animation: AllAnimations;
  duration: string;
  width: string;
};

const getAnimation = (animationName: AllAnimations) => {
  switch (animationName) {
    case 'FadeInFwd':
      return FadeInFwd;
    default:
      return FadeInFwd;
  }
};

export const AnimationContainer = styled.div<AnimationType>`
  animation-name: ${({ animation }) => getAnimation(animation)};
  animation-duration: ${({ duration }) => duration};
  width: ${({ width }) => width};
`;
